services:
  redis:
    image: redis:7-alpine
    container_name: rss_redis
    ports:
      - "6379:6379"
    networks:
      - content-agents
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}

  rss-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss_agent_main
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PORT=8086
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - content-agents
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  rss-agent-worker:
    build: .
    command: celery -A core.queue_manager.celery_app worker --loglevel=info --queues=scraping,processing,uploads --concurrency=2
    environment:
      - ROUTER_AGENT_URL=http://router-agent:8080
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - content-agents

  rss-agent-flower:
    build: .
    command: celery -A core.queue_manager.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
    depends_on:
      - redis
    networks:
      - content-agents

volumes:
  redis_data:
    driver: local

networks:
  content-agents:
    external: true
    name: matrix_reloaded_content-agents